name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Recursive Git clone
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install all build dependencies
      run: >
        sudo apt-get install -y
        build-essential autoconf automake libtool
        libglib2.0-dev libncurses-dev
        groff doxygen
    - name: Generate ./configure
      run: autoreconf -i
    - run: ./configure --with-interface=ncurses --enable-html-manual
    - run: make
    - name: Run test suite
      run: make check
    - name: Build developer documentation
      run: cd doc && make devdoc
# FIXME: Will try to perform an out-of-tree build which will not
# work without manual intervention due to Scintilla.
#    - run: make distcheck
