# After every push with successful CI,
# post the commits since the last successful CI into the IRC channel.
name: IRC Post

on:
  workflow_run:
    workflows: ['Continuous Integration']
    types: [completed]
    branches: master

jobs:
  irc:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Git Clone
      uses: actions/checkout@v4.1.6
    - name: Get last successful commit
      uses: nrwl/last-successful-commit-action@v1
      id: last_successful_commit
      with:
        branch: 'master'
        workflow_id: 'ci.yml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get log
      id: get_log
      run: |
        echo 'log<<EOF' >>$GITHUB_OUTPUT
        git log --pretty="format:%h %s" --reverse \
                ${{ steps.last_successful_commit.outputs.commit_hash }}..HEAD`" >>$GITHUB_OUTPUT
        echo 'EOF' >>$GITHUB_OUTPUT
    - name: Post IRC message
      uses: rectalogic/notify-irc@v1
      with:
        channel: "#sciteco"
        server: "irc.libera.chat"
        nickname: git-bot
        message: ${{ steps.get_log.outputs.log }}
